### ISSUE TITLE
update-vp workflow does not sync the Rust toolchain pin with upstream rust-toolchain.toml (build breaks on upstream nightly bumps)

### ISSUE THREAD

**Issue by naitokosuke** [naitokosuke/vp-nix#73]
## Summary

The scheduled `update-vp.yml` workflow bumps the vite-plus version and recomputes the Nix hashes, but it **never updates the pinned Rust nightly toolchain** in `flake.nix` (nor refreshes the `rust-overlay` input in `flake.lock`).

vite-plus pins its required nightly in `rust-toolchain.toml`, and upstream bumps it periodically. When that happens, the auto-generated update PR carries a stale toolchain pin and the **Verify build** step fails to compile.

This already happened with **v0.1.23**, which moved `rust-toolchain.toml` from `nightly-2025-12-11` to `nightly-2026-05-24` and started using the `c_variadic` `VaList::next_arg` API:

```
error[E0599]: no method named `next_arg` found for struct `VaList<'a>`
error: could not compile `fspy_preload_unix` (lib) due to 7 previous errors
```

See #70 for the original incident; #72 fixed it manually. Without fixing the workflow itself, **this will recur** the next time upstream bumps its nightly.

## Proposed fix

In the `Update flake.nix` step, before computing the hashes / verifying the build:

1. Fetch upstream `rust-toolchain.toml` for the target tag and extract the `nightly-YYYY-MM-DD` channel.
2. If it differs from the pin in `flake.nix`, update both the pin and its documenting comment.
3. Run `nix flake update rust-overlay` so the newly required nightly toolchain is available.

This keeps the toolchain pin automatically in sync with upstream, so the auto-update PRs build green on their own.

## Notes

- The toolchain must be synced *before* the `pnpmDepsHash` / `cargoVendorHash` computation steps, since `cargo vendor` output (and thus `cargoVendorHash`) depends on the cargo version.
- `flake.lock` (the `rust-overlay` bump) is committed as part of the same auto-update PR.
